# Change these first
owner: fsphys # Your GitHub username
repo: status.fsphys.de # Your GitHub repository name

# Add your sites here
sites:
  - name: FS - Website
    url: https://fachschaft.physik.kit.edu
  - name: FS - GitLab
    url: https://fs.physik.kit.edu/gitlab/
  - name: FS - Mattermost
    url: https://fsmm.physik.kit.edu/
  - name: FS - Etherpad
    url: https://fachschaft.physik.kit.edu/pad/
  - name: Platform - Jitsi
    url: https://meet.physik.kit.edu
  - name: Platform - Matrix Webclient
    url: https://matrix.physik.kit.edu
  - name: Platform - Landing Page
    url: https://platform.physik.kit.edu
  - name: Platform - CodiMD
    url: https://platform.physik.kit.edu/codimd/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.fsphys.de
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://fs.physik.kit.edu/static/img/fslogo.svg
  name: FS-Status
  introTitle: "Status der Webservices der Fachschaft Physik am KIT"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/fsphys/status.fsphys.de). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  links:
    - rel: stylesheet
      href: https://status.fsphys.de/custom.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
